home/urls.py
from django.conf.urls import url
from . import views

app_name='home'

urlpatterns = [
    #url(r'^$', views.home, name='home'),
    url(r'^login/$', views.loginview, name='login'),
    url(r'^signup/$', views.signupview, name='signup'),
    url(r'^logout/$', views.logoutview, name='logout'),
]

mubunotes/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^', include('notes.urls', namespace='notes', app_name='notes')),
]

notes/urls.py
from django.conf.urls import url
from . import views

app_name = 'notes'

urlpatterns = [
    url(r'^$', views.notes_list, name="list"),
    url(r'^add/$', views.notes_add, name="add"),
    url(r'^delete/(?P<id>[\d]+)/$', views.notes_delete, name="delete"),
    url(r'^edit/(?P<id>[\d]+)/$', views.notes_edit, name="edit"),
]

home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

    

notes/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import User

# Create your models here.
    
class Note(models.Model):
    username= models.ForeignKey(User, default=None)
    title = models.CharField(max_length=30)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    edited = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

notes/forms.py
from django import forms
from . import models

class AddNote(forms.ModelForm):
    class Meta:
        model = models.Note
        fields = ['title', 'content',]

home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

#added for http response

from django.http import HttpResponse

#get model class from models file
from notes.models import Note

from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.

def home(request):
    notes = Note.objects.all().order_by('date')
    return render(request, 'home.html', {'notes': notes})

def signupview(request):
    if request.method == 'POST':
         form = UserCreationForm(request.POST)
         if form.is_valid():
             user = form.save()
             login(request, user)
             return redirect('notes:list')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', { 'form': form })

def loginview(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            print('form is valid')
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                print('hitting if block with login')
                return redirect(request.POST.get('next'))
            else:
               print('hitting else block with login')
               return redirect('notes:list')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', { 'form': form })

def logoutview(request):
    if request.method == 'POST':
            logout(request)
            return redirect('home:login')

notes/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Note
from django.contrib.auth.decorators import login_required
from . import forms


@login_required(login_url="login/")
def notes_list(request):
    notes = Note.objects.filter(username=request.user);
    return render(request, 'notes_list.html', { 'notes': notes })


@login_required(login_url="login/")
def notes_add(request):
    if request.method == 'POST':
        form = forms.AddNote(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.username = request.user
            instance.save()
            return redirect('notes:list')
    else:
        form = forms.AddNote()
    return render(request, 'notes_add.html', { 'form': form })

@login_required(login_url="login/")
def notes_edit(request, id):
    if request.method == 'POST':
        form = forms.AddNote(request.POST)
        if form.is_valid():
            instance=Note.objects.get(id=id)
            instance.title=request.POST.get('title')
            instance.content=request.POST.get('content')
            instance.save()
            return redirect('notes:list')
    else:
        instance = Note.objects.get(id=id)
        data = {'title': instance.title, 'content': instance.content}
        print('constructed dictionary')
        form = forms.AddNote(data)
        print('form created beginning render')
    return render(request, 'notes_edit.html', { 'form': form, 'id':id })
    

@login_required(login_url="login/")
def notes_delete(request, id):
    instance = Note.objects.get(id=id)
    instance.delete()
    notes = Note.objects.filter(username=request.user)
    return redirect('notes:list')

home/templates/home.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>MubuNotes</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Cookie|Courgette|Dancing+Script|Indie+Flower|Pacifico|Tangerine&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <script src="{% static 'main.js' %}"></script>
    </head>
    <body>
        <header class="wrapper">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <h3><a href="{% url 'notes:list' %}" class="nav-item"><img src="{% static 'logo.png' %}" alt="mubunotes" title="logo"/></a></h3>
                <div class="container col-md-offset-4 col-md-4 d-flex justify-content-center"><h5 class="nav-item"><a href="{% url 'notes:list' %}" class="navbar-brand appheading">MubuNotes</a></h5></div>
               
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <form class="logout-link" action="{% url 'home:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="nav-link">Logout</button>
                        </form>
                    </li>
                    {% else %}
                    <li class="nav-item"><a href="{% url 'home:login' %}" class="nav-link">Login</a></li>
                    <li class="nav-item"><a href="{% url 'home:signup' %}" class="nav-link">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

home/templates/login.html
{% extends 'home.html' %}

{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'home:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <input type="submit" value="Login" />
    </form>
    <p>Not got an account? <a href="">Sign Up</a></p>
{% endblock %}

home/templates/signup.html
{% extends 'home.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="{% url 'home:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

notes/templates/notes_add.html
{% extends 'home.html' %}

{% block content %}
    <div class="add-note row d-flex justify-content-center">
        <h2>Add a New Note</h2>
    </div>
    <div class="container col-md-offset-3 col-md-4">
        <form class="site-form" action="{% url 'notes:add' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row d-flex flex-column justify-content-center">
                {{ form }}
                <input type="submit" value="Add" class="btn btn-success" style="margin-top: 7px;">
            </div>
        </form>
    </div>
    <!-- <script src="/static/main.js"></script> -->
{% endblock %}

notes/templates/notes_edit.html
{% extends 'home.html' %}

{% block content %}
    <div class="add-note row d-flex justify-content-center">
        <h2>Edit Note</h2>
    </div>
    <div class="container col-md-offset-3 col-md-4">
        <form class="site-form" action="{% url 'notes:edit' id=id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row d-flex flex-column justify-content-center">
                {{ form }}
            <input type="submit" value="Update" class="btn btn-success" style="margin-top: 7px;">
            </div>
        </form>
    </div>
{% endblock %}

notes/templates/notes_list.html
{% extends 'home.html' %}

{% block content%}
    <div class="container" style="padding: 10px; margin-top: 20px;">
        <div class="row d-flex justify-content-center">
                <h2><a class="addnote_heading" href="{% url 'notes:add' %}"><span class="fa fa-plus" style="color:green;"></span>Add A New Note</a></h2>
        </div>
            <div class="row"><h1 class="yourNotes">Your Notes</h1></div>
            <div class="notes">
            {% for note in notes %}
                <div class="card border-dark mb-3">
                    <div class="card-body text-dark">
                        <h5 class="card-title">{{ note.title }}</h5>
                        <p class="card-text text-truncate">{{ note.content }}</p>
                        <p  class="card-text"><span style="font-weight: 600;"> Last Updated: </span> {{ note.edited }}</p>
                        <div class="row d-flex justify-content-center">
                            <a href="{% url 'notes:edit' id=note.id %}" class="btn btn-warning" style="margin-right: 5px;">Edit</a>
                            <a href="{% url 'notes:delete' id=note.id %}" class="btn btn-danger" style="margin-left: 5px;">Delete</a>
                        </div>
                    </div>
                </div>
            {% empty %}
                <div class="row d-flex justify-content-center">
                    <h4 style="font-family: 'Courgette', cursive; color: brown;">You have not added any notes!</h4>
                </div>
            {% endfor %}
            
            </div>
        </div>
{% endblock %}